version: 0.0
os: linux

files:
   - source: /test.jsp ### CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 루트로 지정
     destination: /home/ec2-user/tomcat/webapps/ROOT
#    - source: /index.html
#      destination: /var/www/html

permissions: # CodeDeploy에서 EC2서버로 넘겨준 파일들은 모두 ec2-user권한을 갖도록 설정
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root
